image:
  repository: gcr.io/google-containers/fluentd-elasticsearch
  tag: v2.0.1
  pullPolicy: IfNotPresent

env:
- name: FLUENTD_ARGS
  value: --no-supervisor -q
- name: FLUENT_ELASTICSEARCH_HOST
  value: "elasticsearch"
- name: FLUENT_ELASTICSEARCH_PORT
  value: "9200"

tolerations: []

nodeSelector: {}

metadata:
  name: fluentd-es
  labels:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile

volumeMounts:
- name: varlog
  mountPath: /var/log
- name: varlibdockercontainers
  mountPath: /var/lib/docker/containers
  readOnly: true
- name: journal
  mountPath: /run/log/journal
- name: config
  mountPath: /etc/fluent/config.d

volumes:
- name: varlog
  hostPath:
    path: /var/log
- name: varlibdockercontainers
  hostPath:
    path: /var/lib/docker/containers
- name: journal
  hostPath:
    path: /run/log/journal
- name: config
  configMap:
    name: fluentd-es-config

resources:
  limits:
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi
