image:
  repository: gcr.io/google-containers/elasticsearch
  tag: v5.6.4
  pullPolicy: IfNotPresent

env:
- name: "NAMESPACE"
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace

ports:
- containerPort: 9200
  name: db
  protocol: TCP
- containerPort: 9300
  name: transport
  protocol: TCP

volumeMounts:
- name: elasticsearch-logging
  mountPath: /data

volumes:
- name: elasticsearch-logging
  emptyDir: {}

storage:
  name: standardSSD
  provisioner: kubernetes.io/aws-ebs
  storageType: gp2
  availabilityZone: us-east-1a
  size: 10Gi

metadata:
  name: elasticsearch-logging
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile

resources:
  limits:
    cpu: 1000m
  requests:
    cpu: 200m

replicaSlaves: 2
replicaMaster: 1
